spring:
  application:
    name: xianyu-client
  cloud:
      nacos:
        discovery:
          username: nacos
          password: nacos
          server-addr: 192.168.146.131:8848

logging:
  level:
    feign.Logger: debug